# Application identity
info.app.environment=testing

server.port=8082

cgw.tcp.port=9000

kafka.enabled=true
spring.kafka.producer.bootstrap-servers: 192.168.100.251:9092
spring.kafka.consumer.bootstrap-servers: 192.168.100.251:9092
spring.kafka.consumer.group-id: group-gps-data

#DB props....
spring.datasource.url=jdbc:postgresql://192.168.100.251:5432/fleetnode_101
spring.datasource.username=enterprisedb
spring.datasource.password=adm123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


packet.devices.dLite.sep=,
packet.devices.dLite.mapping=txt_instrument_id:5,txt_resources:6,num_latitude:10,num_longitude:12,int_current_speed:15

logging.file.path=/opt/logs/device-data-handler
