server.port=8080

# VERY IMPORTANT
#spring.main.web-application-type=servlet

# Actuator
#management.server.port=8080
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always

cgw.tcp.port=9000

spring.kafka.producer.bootstrap-servers: localhost:9092
spring.kafka.consumer.bootstrap-servers: localhost:9092
spring.kafka.consumer.group-id: group-gps-data



packet.dLite.sep=,
packet.dLite.mapping=txt_instrument_id:2,txt_resources:3,num_latitude:5,num_longitude:6,int_current_speed:7

