apiVersion: v1
kind: Service
metadata:
  name: device-data-handler-service
spec:
  selector:
    app: device-data-handler
  ports:
    - name: app-port
      port: 8081
      targetPort: 8082
      nodePort: 8081
    - name: cgw-port
      port: 9000
      targetPort: 9000
      nodePort: 9000
  type: NodePort